### ISSUE TITLE
Debug rfswarm-manager on github runner

### ISSUE THREAD

**Issue by KseniaYa** [Esthenia-collaboration/rfswarm-docker#46]
Problem encountered - no manager logs in the runner.

- Test with installation of the packages (tkinter) and run on headless mode based on ubuntu: https://github.com/Esthenia-collaboration/rfswarm-docker/actions/runs/10421301094/job/28863210696
- packages installed and run with "-n" option: https://github.com/Esthenia-collaboration/rfswarm-docker/actions/runs/10421360086/job/28863403211
- run with "-n" option on windows: https://github.com/Esthenia-collaboration/rfswarm-docker/actions/runs/10431012752/job/28890223797

**Comment by damies13** [comment]
This is what I mentioned about I wasn't sure what would happen, but I suspected nothing if you run with only -n. 

the error `Error: The operation was canceled.` is because the manager didn't exit, and the no logs is because you force stopped the manager (Areck worked on some changes to make this better in v1.4.0, but it will still happen).

Th reason the manager never exits is the manager doesn't know what to do because you didn't give it any scenario to run:
- you just installed the manager so there is no ini file in the default location with a previous scenario to load
- you didn't pass the -i option to specify an ini file with a previous scenario to load
- you didn't pass the -s option to specify a scenario to run

so you don't need to setup a new scenario and robot for testing, you can reuse any from the [rfswarm regression suite](https://github.com/damies13/rfswarm/tree/v1.4.0/Tests/Regression/), I'd suggest [this one](https://github.com/damies13/rfswarm/tree/v1.4.0/Tests/Regression/Agent/testdata/Issue-%23171) as a nice simple test that will take less than 2 min to run after the agent connects to the manager.

**Comment by Maresther-B** [comment]
After applying Daves's remarques it seems the issue was caused by a wrong test case called in the manager scenario.rfs file. 
Is it ok for you @KseniaYa  if I re assigned you this issue?
